### ISSUE TITLE
BUG: Object literal may only specify known properties, and 'ref' does not exist in type 'Partial<unknown> & Attributes'.

### ISSUE THREAD

**Issue by kotAPI** [rad-ui/ui#622]
## Description

We have a couple of tests failing with an error reading

```
 src/core/primitives/Primitive/index.tsx:19:68 - error TS2769: No overload matches this call.
      The last overload gave the following error.
        Object literal may only specify known properties, and 'ref' does not exist in type 'Partial<unknown> & Attributes'.

    19             return React.cloneElement(children, { ...elementProps, ref });
```
Possibly introduced in https://github.com/rad-ui/ui/pull/583
